# Generated by Django 3.2.8 on 2023-05-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_post', '0001_initial'),
        ('api_interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_rating', to='api_post.posts'),
        ),
    ]
