export enum ActionTypes {
  // Authentication
  GET_TOKEN_INFO = "GET_TOKEN_INFO",
  SET_TOKEN_INFO = "SET_TOKEN_INFO",
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",

  // USER
  GET_USER_INFO = "GET_USER_INFO",
  GET_USER_PROFILE = "GET_USER_PROFILE",
  UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE",

  // CAMPAIGN
  FETCH_CAMPAIGNS = "FETCH_CAMPAIGNS",
  FETCH_CAMPAIGN_DETAIL = "FETCH_CAMPAIGN_DETAIL",
  FETCH_CAMPAIGN_MANAGEMENT = "FETCH_CAMPAIGN_MANAGEMENT",
  CREATE_CAMPAIGN = "CREATE_CAMPAIGN",
  UPDATE_CAMPAIGN_INFO = "UPDATE_CAMPAIGN_INFO",
  DELETE_CAMPAIGN = "DELETE_CAMPAIGN",

  // CAMPAIGN POST
  CREATE_CAMPAIGN_POST = "CREATE_CAMPAIGN_POST",
  CREATE_CAMPAIGN_POST_COMMENT = "CREATE_CAMPAIGN_POST_COMMENT",

  // TOPIC
  FETCH_TOPICS = "FETCH_TOPICS",
  ADD_TOPIC = "ADD_TOPIC",
  UPDATE_TOPIC = "UPDATE_TOPIC",
  DELETE_TOPIC = "DELETE_TOPIC",

  //RATING
  CREATE_RATING = "CREATE_RATING",
  FETCH_RATINGS = "FETCH_RATINGS",
  //PROCESS
  FETCH_CAMPAIGN_PROCESS_DETAIL = "FETCH_CAMPAIGN_PROCESS_DETAIL",
  UPDATE_CAMPAIGN_PROCESS = "UPDATE_CAMPAIGN_PROCESS",
  FETCH_USER_CAMPAIGNS_PROCESS = "FETCH_USER_CAMPAIGNS_PROCESS",

  //TRANSACTION
  CREATE_TRANSACTION = "CREATE_TRANSACTION",
}
