# Generated by Django 3.2.8 on 2023-06-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER'), ('AUTHOR', 'AUTHOR')], default='USER', max_length=50),
        ),
    ]
