# Generated by Django 3.2.8 on 2023-04-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
