# Generated by Django 3.2.8 on 2023-05-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_post', '0001_initial'),
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='api_user.User'),
        ),
        migrations.AddField(
            model_name='posts',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api_post.source'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api_post.posts'),
        ),
        migrations.AddField(
            model_name='contents',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api_post.posts'),
        ),
    ]
