# Generated by Django 3.2.8 on 2023-06-05 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0003_posts_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vector', models.BinaryField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_post.posts')),
            ],
            options={
                'db_table': 'post_vector',
                'ordering': ['-created_at'],
            },
        ),
    ]
