# Generated by Django 3.2.8 on 2023-05-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0004_postvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvector',
            name='vector',
            field=models.BinaryField(),
        ),
    ]
