# Generated by Django 3.2.8 on 2023-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0005_auto_20230610_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('PENDING', 'PENDING')], default='DRAFT', max_length=50),
        ),
    ]
