# Generated by Django 3.2.8 on 2023-06-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0005_alter_postvector_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api_post.source'),
        ),
    ]
